spring:
  application:
    name: elastic-bot

  datasource:
    url: jdbc:postgresql://localhost:5432/bgau_assistant_bot
    username: bunker
    password: bunker

  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/bgau_assistant_bot
    user: bunker
    password: bunker

bots:
  telegram:
    token: 6400904135:AAH_j-D2lWY3QlJGDqU7d_A9N1O57gCcpUg